### ISSUE TITLE
README buries the lede

### ISSUE THREAD

**Issue by standage** [mikldk/DNAtools#2]
The first three lines of the "Getting started" section of the main README are, in my opinion, the content that any potential user needs to see first. Installation instructions, issue trackers, examples, etc., are all good, but first and foremost a user needs to see **What does this software do? Who is it designed for?**

In general I think the documentation for DNAtools is very good, but I think this change would make it even better for newcomers.

**Comment by mikldk** [comment]
Good point. Thank you. Please see b08a86df031e13a634373ddb6e10c169fee00cdf. I hope this addresses this issue?

**Comment by standage** [comment]
LGTM!
